### ISSUE TITLE
Add image uploader to recipe form

### ISSUE THREAD

**Issue by adam-coogan** [lhenn/tasty-base#10]
Ideally it should be possible to add/remove/reorder images when creating and editing post. At minimum it should be possible to add images when creating a post.

**Comment by lhenn** [comment]
All the old functionality of uploading images/displaying them as a gallery has been uncommented out. Additionally you can now view existing images in the gallery and add to them when editing a post  (rather than replacing everything). 

What still needs to be done:
- [ ] Decide on how users should be able to remove images (maybe update the tooltip to be able to do this as well as set the cover image?)
- [ ] Implement delete images functionality
- [ ] Fix the buggy tooltip status
- [ ] (Nice to have): Refactor out gallery component and gallery editor to be it's own recipe-atom

I think being able to reorder images is a true luxury that I don't have the patience to implement.

**Comment by lhenn** [comment]
Images can be deleted now, but we need to handle a few more situations:

- [ ] If an image is deleted that is a cover image, remove the cover image
- [ ] If a post is deleted, remove images in gallery
